"""empty message

Revision ID: e7338be321e3
Revises: 71ea301252e4
Create Date: 2022-05-10 10:14:51.786271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7338be321e3'
down_revision = '71ea301252e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('human_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cat', 'human', ['human_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cat', type_='foreignkey')
    op.drop_column('cat', 'human_id')
    # ### end Alembic commands ###
